[theme]

# Customize theme with 'base'
# base="light"
# base="dark"

# Primary accent for interactive elements
primaryColor = '#2B2B2B'

# Background color for the main content area
backgroundColor = '#5D2B97'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#78787D'

# Color used for almost all text
textColor = '#FAFAFA'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font="sans serif"